//
// Created by bertan on 2.11.2023.
//

#ifndef PRODUCERCONSUMERPATTERNBLOGPOST_FRAMEQUEUE_H
#define PRODUCERCONSUMERPATTERNBLOGPOST_FRAMEQUEUE_H


class FrameQueue
{

};


#endif //PRODUCERCONSUMERPATTERNBLOGPOST_FRAMEQUEUE_H
