//
// Created by bertan on 3.11.2023.
//

#ifndef PRODUCERCONSUMERPATTERNBLOGPOST_WORKERTHREAD_H
#define PRODUCERCONSUMERPATTERNBLOGPOST_WORKERTHREAD_H


class WorkerThread
{

};


#endif //PRODUCERCONSUMERPATTERNBLOGPOST_WORKERTHREAD_H
